# Generated by Django 6.0.6 on 2026-06-30 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("bairro", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("especie", models.CharField(max_length=50)),
                ("raca", models.CharField(max_length=50)),
                (
                    "porte",
                    models.CharField(
                        choices=[
                            ("Pequeno", "Pequeno"),
                            ("Médio", "Médio"),
                            ("Grande", "Grande"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Confirmado", "Confirmado"),
                            ("Concluído", "Concluído"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="kerberos.pet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServicoAgendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agendamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kerberos.agendamento",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kerberos.servico",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agendamento",
            name="servicos",
            field=models.ManyToManyField(
                through="kerberos.ServicoAgendamento", to="kerberos.servico"
            ),
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(max_length=15)),
                (
                    "endereco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kerberos.endereco",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pet",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kerberos.usuario"
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="kerberos.usuario",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicoagendamento",
            constraint=models.UniqueConstraint(
                fields=("agendamento", "servico"), name="unique_servico_agendamento"
            ),
        ),
    ]
