# Generated by Django 6.0.6 on 2026-10-07 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kerberos", "0005_alter_pet_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={},
        ),
        migrations.AlterField(
            model_name="pet",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tutor",
            ),
            preserve_default=False,
        ),
    ]
