# Generated by Django 6.0.6 on 2026-10-08 20:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kerberos", "0006_alter_pet_options_alter_pet_usuario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="endereco",
            options={
                "ordering": ["-id"],
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
        ),
        migrations.RemoveField(
            model_name="endereco",
            name="rua",
        ),
        migrations.AddField(
            model_name="endereco",
            name="cidade",
            field=models.CharField(
                default="Não informada", max_length=100, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="endereco",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="endereco",
            name="logradouro",
            field=models.CharField(
                default="sem informação", max_length=150, verbose_name="Logradouro/Rua"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="endereco",
            name="uf",
            field=models.CharField(
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                default="SP",
                max_length=2,
                verbose_name="UF",
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="bairro",
            field=models.CharField(max_length=100, verbose_name="Bairro"),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="cep",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CEP inválido. Use o formato 00000-000 ou apenas números.",
                        regex="^\\d{5}-?\\d{3}$",
                    )
                ],
                verbose_name="CEP",
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="numero",
            field=models.CharField(
                default="S/N",
                help_text="Digite o número ou S/N",
                max_length=20,
                verbose_name="Número",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="endereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="kerberos.endereco",
            ),
        ),
    ]
