# Generated by Django 6.0.6 on 2026-10-08 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kerberos", "0007_alter_endereco_options_remove_endereco_rua_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pet",
            name="nome",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Nome do Pet"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="porte",
            field=models.CharField(
                choices=[
                    ("Pequeno", "Pequeno"),
                    ("Médio", "Médio"),
                    ("Grande", "Grande"),
                ],
                max_length=20,
                verbose_name="Porte",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="raca",
            field=models.CharField(max_length=50, verbose_name="Raça"),
        ),
    ]
