# Generated by Django 6.0.6 on 2026-10-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kerberos", "0008_alter_pet_options_pet_atualizado_em_pet_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="kerberos.usuario",
                verbose_name="Tutor",
            ),
        ),
    ]
