# Generated by Django 6.0.6 on 2026-10-09 19:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kerberos", "0009_alter_pet_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemAgendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servico_nome", models.CharField(max_length=100)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("duracao_minutos", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Item do Agendamento",
                "verbose_name_plural": "Itens do Agendamento",
            },
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="servicos",
        ),
        migrations.AddField(
            model_name="servico",
            name="ativo",
            field=models.BooleanField(
                default=True,
                help_text="Desmarque para desativar o serviço sem apagar o histórico",
                verbose_name="Ativo",
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servico",
            name="duracao_minutos",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Tempo médio necessário para realizar o serviço",
                validators=[
                    django.core.validators.MinValueValidator(
                        5, message="A duração mínima é de 5 minutos."
                    )
                ],
                verbose_name="Duração estimada (minutos)",
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada do que está incluso no serviço",
                null=True,
                verbose_name="Descrição",
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="nome",
            field=models.CharField(
                help_text="Ex: Banho e Tosa, Corte de Unha, Tosa Higiênica",
                max_length=100,
                unique=True,
                verbose_name="Nome do Serviço",
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01"),
                        message="O valor deve ser de no mínimo R$ 0,01.",
                    )
                ],
                verbose_name="Preço (R$)",
            ),
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(
                fields=["ativo", "nome"], name="kerberos_se_ativo_8f22a5_idx"
            ),
        ),
        migrations.AddField(
            model_name="itemagendamento",
            name="agendamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="kerberos.agendamento",
            ),
        ),
        migrations.AddField(
            model_name="itemagendamento",
            name="servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_agendados",
                to="kerberos.servico",
            ),
        ),
    ]
